[package]
name = "render"
version.workspace = true
edition.workspace = true

[dependencies]
geodesy.workspace = true
tilestore.workspace = true
terragen.workspace = true
h5.workspace = true
glam.workspace = true
serde.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
rayon.workspace = true
parking_lot.workspace = true
image.workspace = true
