use crate::Common;
use anyhow::{bail, Context, Result};
use clap::Args;
use geodesy::tiles::{tiles_in_bounds, LatLonBounds, TileId};
use indicatif::{ProgressBar, ProgressStyle};
use render::dynamics;
use render::pipeline;
use render::scenario::Scenario;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use terragen::Generator;
use tilestore::TileStore;

pub(crate) fn setup(c: &Common) -> Result<Scenario> {
    if let Some(n) = c.threads {
        rayon::ThreadPoolBuilder::new().num_threads(n).build_global().ok();
    }
    let mut s = Scenario::load_or_default(c.config.as_deref())?;
    if let Some(seed) = c.seed {
        s.world.seed = seed;
    }
    Ok(s)
}

fn bar(len: usize, what: &str) -> ProgressBar {
    let b = ProgressBar::new(len as u64);
    b.set_style(ProgressStyle::with_template(&format!("{what} {{bar:40}} {{pos}}/{{len}} [{{elapsed_precise}} < {{eta_precise}}] {{per_sec}}")).unwrap());
    b
}

fn synth(s: &Scenario, out: &Path) -> Result<()> {
    let gen = Generator::new(s.world.clone());
    let home = s.world.home.clone().unwrap_or_default();
    let ell = gen.world.ell;
    // ground reference for AGL flights: smooth terrain sampled at ~200 m resolution
    let ground = |lat: f64, lon: f64| -> f64 {
        let t = gen.world.terrain(&terragen::world::Ctx::new(lat, lon, 200.0, &ell));
        if t.water_kind != 0 { t.water.max(t.ground) } else { t.ground }
    };
    let t0 = std::time::Instant::now();
    let recs = dynamics::simulate(&s.trajectory.synth, (home.lat, home.lon), &ell, Some(&ground));
    let note = format!("generated by `terrain run --step traj` with:\n{}", serde_yaml::to_string(&s.trajectory.synth)?);
    dynamics::save_records(out, &recs, &note)?;
    let first = &recs[0].pose;
    let last = &recs[recs.len() - 1].pose;
    eprintln!(
        "wrote {} samples ({:.1} s) to {} in {:.2}s; start {:.5},{:.5} h={:.0} m, end {:.5},{:.5} h={:.0} m",
        recs.len(),
        last.t,
        out.display(),
        t0.elapsed().as_secs_f64(),
        first.geo.lat.to_degrees(),
        first.geo.lon.to_degrees(),
        first.geo.h,
        last.geo.lat.to_degrees(),
        last.geo.lon.to_degrees(),
        last.geo.h
    );
    Ok(())
}

fn load_poses(s: &Scenario) -> Result<Vec<render::Pose>> {
    let ell = geodesy::Ellipsoid::from_a_invf(s.world.planet.a, s.world.planet.inv_f);
    let p = render::trajectory::load(&s.trajectory.file, &ell).with_context(|| "loading the trajectory (`terrain run --step traj` makes one)")?;
    if p.is_empty() {
        bail!("trajectory {} is empty", s.trajectory.file.display());
    }
    Ok(p)
}

fn plan_tiles(s: &Scenario, gen: &Generator) -> Result<BTreeSet<TileId>> {
    let poses = load_poses(s)?;
    let t0 = std::time::Instant::now();
    let set = pipeline::plan(s, &poses, Some(gen))?;
    let mut per_zoom = std::collections::BTreeMap::new();
    for t in &set {
        *per_zoom.entry(t.z).or_insert(0usize) += 1;
    }
    eprintln!("planned {} tiles for {} camera(s) in {:.2}s: {:?}", set.len(), s.cameras.len(), t0.elapsed().as_secs_f64(), per_zoom);
    Ok(set)
}

fn parse_tile_list(p: &Path) -> Result<Vec<TileId>> {
    let mut v = Vec::new();
    for l in std::fs::read_to_string(p)?.lines() {
        let l = l.trim();
        if l.is_empty() || l.starts_with('#') {
            continue;
        }
        let f: Vec<u32> = l.split('/').map(|s| s.trim().parse()).collect::<Result<_, _>>()?;
        if f.len() != 3 {
            bail!("bad tile line {l}");
        }
        v.push(TileId::new(f[0] as u8, f[1], f[2]));
    }
    Ok(v)
}

fn gen_tiles(s: &Scenario, gen: &Generator, tiles: Vec<TileId>, force: bool) -> Result<()> {
    let store = pipeline::open_or_create_store(s, gen)?;
    let b = bar(0, "gen");
    let t0 = std::time::Instant::now();
    let n = pipeline::generate(gen, &store, &tiles, force, &|done, total| {
        b.set_length(total as u64);
        b.set_position(done as u64);
    })?;
    b.finish();
    eprintln!("generated {n} tiles ({} requested) in {:.1}s → {} ({} tiles total)", tiles.len(), t0.elapsed().as_secs_f64(), s.tiles.file.display(), store.len());
    Ok(())
}

fn open_store(s: &Scenario, gen: &Generator) -> Result<Arc<TileStore>> {
    let store = if s.tiles.lazy {
        pipeline::open_or_create_store(s, gen)?
    } else {
        gen.open_store_ro(&s.tiles.file).with_context(|| "opening the tile store (`terrain tiles` generates it; or use --lazy)")?
    };
    Ok(Arc::new(store))
}

fn do_render(s: &Scenario) -> Result<()> {
    if s.cameras.is_empty() && s.imu.is_none() {
        bail!("nothing to render: the scenario has no `cameras` and no `imu`");
    }
    let poses = load_poses(s)?;
    let gen = Arc::new(Generator::new(s.world.clone()));
    let store = open_store(s, &gen)?;
    let b = bar(0, "render");
    b.set_style(ProgressStyle::with_template("render {msg:12} {bar:40} {pos}/{len} [{elapsed_precise} < {eta_precise}] {per_sec}").unwrap());
    let t0 = std::time::Instant::now();
    let rep = pipeline::render_sequence(s, &poses, store, Some(gen), &|cam, done, total| {
        b.set_message(cam.to_string());
        b.set_length(total as u64);
        b.set_position(done as u64);
    })?;
    b.finish();
    let out = s.output.file.display();
    eprintln!("rendered in {:.1}s → {out}", t0.elapsed().as_secs_f64());
    eprintln!("  {}: {} body poses at {} Hz", s.output.pose.path, rep.pose_samples, s.output.pose.rate_hz);
    if let (Some(imu), Some(n)) = (&s.imu, rep.imu_samples) {
        eprintln!("  {}: {n} IMU samples at {} Hz", imu.path, imu.rate_hz);
    }
    for (cam, n) in &rep.frames {
        eprintln!("  {cam}: {n} frames");
    }
    Ok(())
}

fn do_events(s: &Scenario) -> Result<()> {
    if !s.cameras.iter().any(|c| c.events.is_some()) {
        bail!("no camera has an `events` modality");
    }
    let poses = load_poses(s)?;
    let gen = Arc::new(Generator::new(s.world.clone()));
    let store = open_store(s, &gen)?;
    let b = ProgressBar::new(1000);
    b.set_style(ProgressStyle::with_template("events {msg:12} {bar:40} {percent}% [{elapsed_precise} < {eta_precise}]").unwrap());
    let t0 = std::time::Instant::now();
    let res = pipeline::render_events(s, &poses, store, Some(gen), &|cam, done, total| {
        b.set_message(cam.to_string());
        b.set_position((1000.0 * done / total.max(1e-9)) as u64);
    })?;
    b.finish();
    eprintln!("simulated events in {:.1}s → {}", t0.elapsed().as_secs_f64(), s.output.file.display());
    for (cam, st) in &res {
        eprintln!(
            "  {cam}/events: {} events; {} renders ({:.1}s), {} sensor steps ({:.1}s)",
            st.events, st.renders, st.render_s, st.steps, st.step_s
        );
    }
    Ok(())
}

/// Dry runs of the renderer's tile selection with the generated tiles' real elevation ranges,
/// generating what they add (with margins), until nothing is missing.
fn complete_tiles(s: &Scenario, gen: &Generator) -> Result<()> {
    let poses = load_poses(s)?;
    // one zoom level of tiles with unknown elevation per pass (see TileOracle::refine_unknown)
    for pass in 1..=24 {
        let missing = {
            let store = pipeline::open_or_create_store(s, gen)?;
            pipeline::plan_missing(s, &poses, &store)?
        };
        if missing.is_empty() {
            eprintln!("dry run {pass}: all tiles the renderer selects are stored");
            return Ok(());
        }
        eprintln!("dry run {pass}: {} more tiles", missing.len());
        gen_tiles(s, gen, missing.into_iter().collect(), false)?;
    }
    eprintln!("dry runs did not converge; the rest is generated lazily");
    Ok(())
}

fn stored_tiles(s: &Scenario, gen: &Generator) -> Result<BTreeSet<TileId>> {
    let store = pipeline::open_or_create_store(s, gen)?;
    Ok(store.zooms().into_iter().flat_map(|z| store.tiles_at(z)).collect())
}

// ============================================================================= run

/// The steps of `terrain run`.
#[derive(clap::ValueEnum, Clone, Copy, Debug, PartialEq, Eq)]
pub enum Step {
    Traj,
    Tiles,
    Render,
    Events,
}

#[derive(Args)]
pub struct RunArgs {
    #[command(flatten)]
    pub common: Common,
    /// Only these steps (comma separated): traj (synthesize the flight), tiles (plan and
    /// generate), render (poses, IMU, frames), events. Default: all, keeping an existing
    /// trajectory file.
    #[arg(long, value_delimiter = ',')]
    pub step: Vec<Step>,
    /// Generate tiles the renderer misses while rendering (sets tiles.lazy).
    #[arg(long)]
    pub lazy: bool,
}

pub fn run(a: RunArgs) -> Result<()> {
    let mut s = setup(&a.common)?;
    if a.lazy {
        s.tiles.lazy = true;
    }
    let all = a.step.is_empty();
    let want = |st: Step| all || a.step.contains(&st);
    if want(Step::Traj) && (!all || !s.trajectory.file.exists()) {
        synth(&s, &s.trajectory.file)?;
    }
    let before = if want(Step::Tiles) {
        let gen = Generator::new(s.world.clone());
        let tiles = plan_tiles(&s, &gen)?;
        gen_tiles(&s, &gen, tiles.into_iter().collect(), false)?;
        complete_tiles(&s, &gen)?;
        Some(stored_tiles(&s, &gen)?)
    } else {
        None
    };
    if want(Step::Render) {
        do_render(&s)?;
    }
    let has_events = s.cameras.iter().any(|c| c.events.is_some());
    if want(Step::Events) && (has_events || !all) {
        do_events(&s)?;
    }
    // tiles generated lazily while rendering (event steps between the planned samples) get
    // their neighbourhood too
    if let Some(before) = before {
        let gen = Generator::new(s.world.clone());
        let mut lazy: BTreeSet<TileId> = stored_tiles(&s, &gen)?.difference(&before).copied().collect();
        if !lazy.is_empty() {
            pipeline::with_margin_and_ancestors(&s, &mut lazy);
            eprintln!("neighbourhood of the lazily generated tiles:");
            gen_tiles(&s, &gen, lazy.into_iter().collect(), false)?;
        }
    }
    Ok(())
}

// ============================================================================= tiles

#[derive(Args)]
pub struct TilesArgs {
    #[command(flatten)]
    pub common: Common,
    /// Tiles of a region instead of the flight's: lat_min,lon_min,lat_max,lon_max (deg).
    #[arg(long, allow_hyphen_values = true, help_heading = "Which tiles")]
    pub bbox: Option<String>,
    /// Zoom range of --bbox.
    #[arg(long, default_value = "0-12", help_heading = "Which tiles")]
    pub zooms: String,
    /// Tiles from a list file (one z/x/y per line) instead of the flight's.
    #[arg(long, help_heading = "Which tiles")]
    pub list: Option<PathBuf>,
    /// Only list the tiles (to -o, else stdout); generate nothing.
    #[arg(long)]
    pub dry_run: bool,
    /// Tile list output of --dry-run.
    #[arg(long, short)]
    pub out: Option<PathBuf>,
    /// Regenerate tiles that are already stored.
    #[arg(long)]
    pub force: bool,
    /// Preview instead: generate a mosaic straight into PNGs (<PREFIX>_<layer>.png; no store).
    #[arg(long, value_name = "PREFIX", help_heading = "Preview")]
    pub png: Option<PathBuf>,
    /// Preview: zoom level.
    #[arg(long, default_value_t = 14, help_heading = "Preview")]
    pub zoom: u8,
    /// Preview: mosaic size in tiles per side.
    #[arg(long, default_value_t = 4, help_heading = "Preview")]
    pub size: u32,
    /// Preview: centre lat,lon (deg; default: the world's home).
    #[arg(long, allow_hyphen_values = true, help_heading = "Preview")]
    pub at: Option<String>,
    /// Preview: layers (rgb, albedo, elevation, normal, landcover, hillshade).
    #[arg(long, default_value = "rgb", help_heading = "Preview")]
    pub layers: String,
}

fn parse_floats(s: &str, n: usize, what: &str) -> Result<Vec<f64>> {
    let v: Vec<f64> = s.split(',').map(|x| x.trim().parse()).collect::<Result<_, _>>().with_context(|| format!("{what}: numbers expected"))?;
    if v.len() != n {
        bail!("{what}: {n} comma-separated numbers expected");
    }
    Ok(v)
}

pub fn tiles(a: TilesArgs) -> Result<()> {
    let s = setup(&a.common)?;
    if let Some(prefix) = &a.png {
        let at = a.at.as_deref().map(|v| parse_floats(v, 2, "--at lat,lon")).transpose()?.map(|v| (v[0], v[1]));
        return crate::preview::mosaic(s.world.clone(), at, a.zoom, a.size, &a.layers, prefix);
    }
    let gen = Generator::new(s.world.clone());
    let flight = a.list.is_none() && a.bbox.is_none();
    let tiles: Vec<TileId> = if let Some(t) = &a.list {
        parse_tile_list(t)?
    } else if let Some(bb) = &a.bbox {
        let v = parse_floats(bb, 4, "--bbox lat_min,lon_min,lat_max,lon_max")?;
        let (z0, z1) = a.zooms.split_once('-').map(|(a, b)| (a.parse::<u8>(), b.parse::<u8>())).context("--zooms a-b")?;
        let (z0, z1) = (z0?, z1?);
        let b = LatLonBounds { lat_min: v[0].to_radians(), lon_min: v[1].to_radians(), lat_max: v[2].to_radians(), lon_max: v[3].to_radians() };
        (z0..=z1).flat_map(|z| tiles_in_bounds(&b, z)).collect()
    } else {
        plan_tiles(&s, &gen)?.into_iter().collect()
    };
    if a.dry_run {
        let txt: String = tiles.iter().map(|t| format!("{}/{}/{}\n", t.z, t.x, t.y)).collect();
        match &a.out {
            Some(o) => {
                if let Some(p) = o.parent() {
                    std::fs::create_dir_all(p).ok();
                }
                std::fs::write(o, txt)?;
                eprintln!("wrote {} ({} tiles)", o.display(), tiles.len());
            }
            None => print!("{txt}"),
        }
        return Ok(());
    }
    gen_tiles(&s, &gen, tiles, a.force)?;
    if flight {
        // the renderer's own selection with the real elevation ranges: what it adds
        complete_tiles(&s, &gen)?;
    }
    Ok(())
}

// ============================================================================= view, config

#[derive(Args)]
pub struct ViewArgs {
    #[command(flatten)]
    pub common: Common,
    #[command(flatten)]
    pub view: viewer::ViewOptions,
}

/// The world on a globe (map) and through a camera (the dataset renderer), flown live.
pub fn view(a: ViewArgs) -> Result<()> {
    let s = setup(&a.common)?;
    let gen = Generator::new(s.world.clone());
    let store = pipeline::open_or_create_store(&s, &gen)?;
    viewer::run(s, Arc::new(store), Arc::new(gen), a.view)
}

#[derive(Args)]
pub struct ConfigArgs {
    #[command(flatten)]
    pub common: Common,
    /// Every setting with its default instead of the short template (with -c the whole resolved
    /// scenario is printed anyway). Sections that are off by default (a camera's events, stars)
    /// show their settings only when turned on, e.g. `events: {}` in a scenario given with -c.
    #[arg(long)]
    pub all: bool,
}

/// The main settings, commented: a starting point for a scenario.
pub const TEMPLATE: &str = include_str!("template.yaml");

pub fn config(a: ConfigArgs) -> Result<()> {
    if a.common.config.is_none() && a.common.seed.is_none() && !a.all {
        print!("{TEMPLATE}");
        return Ok(());
    }
    let s = setup(&a.common)?;
    print!("{}", s.to_yaml());
    Ok(())
}

#[derive(Args)]
pub struct InfoArgs {
    pub file: PathBuf,
}

pub fn info(a: InfoArgs) -> Result<()> {
    if let Ok(st) = TileStore::open(&a.file) {
        let m = st.meta();
        println!(
            "tile store {} (seed {}, generator version {}{}, ellipsoid a={} b={:.6})",
            a.file.display(),
            m.seed,
            m.generator_version,
            if m.generator_version == terragen::GENERATOR_VERSION { "" } else { " — not this binary's" },
            m.ellipsoid_a,
            m.ellipsoid_b
        );
        println!("layers: {:?}", m.layers.iter().map(|l| l.name()).collect::<Vec<_>>());
        for z in st.zooms() {
            let t = st.tiles_at(z);
            let (mut lo, mut hi) = (f32::MAX, f32::MIN);
            for id in &t {
                if let Some((a, b)) = st.elev_range(*id) {
                    lo = lo.min(a);
                    hi = hi.max(b);
                }
            }
            println!("  z{z:2}: {:6} tiles  elevation {lo:.0} .. {hi:.0} m", t.len());
        }
        return Ok(());
    }
    let f = h5::File::open(&a.file)?;
    use h5::Attrs;
    println!("{} (format {:?})", a.file.display(), f.attr_str("format").unwrap_or_default());
    fn walk(g: &h5::Group, prefix: &str, depth: usize) -> Result<()> {
        for name in g.member_names()? {
            let path = format!("{prefix}/{name}");
            if let Ok(ds) = g.dataset(&name) {
                println!("{}{path}: {:?}", "  ".repeat(depth), ds.shape()?);
            } else {
                println!("{}{path}/", "  ".repeat(depth));
                walk(&g.group(&name)?, &path, depth + 1)?;
            }
        }
        Ok(())
    }
    walk(&f, "", 1)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The template parses, and every value it shows is the default.
    #[test]
    fn template_shows_the_defaults() {
        let t: Scenario = serde_yaml::from_str(TEMPLATE).expect("template parses");
        t.validate().unwrap();
        let d = Scenario::default();
        assert_eq!(serde_yaml::to_string(&t.world).unwrap(), serde_yaml::to_string(&d.world).unwrap());
        assert_eq!(serde_yaml::to_string(&t.tiles).unwrap(), serde_yaml::to_string(&d.tiles).unwrap());
        assert_eq!(serde_yaml::to_string(&t.trajectory).unwrap(), serde_yaml::to_string(&d.trajectory).unwrap());
        assert_eq!(serde_yaml::to_string(&t.render).unwrap(), serde_yaml::to_string(&d.render).unwrap());
        assert_eq!(serde_yaml::to_string(&t.output).unwrap(), serde_yaml::to_string(&d.output).unwrap());
    }
}
