use crate::Common;
use anyhow::{bail, Context, Result};
use clap::Args;
use geodesy::tiles::{tiles_in_bounds, LatLonBounds, TileId};
use indicatif::{ProgressBar, ProgressStyle};
use render::dynamics;
use render::pipeline;
use render::scenario::Scenario;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use terragen::Generator;
use tilestore::TileStore;

fn setup(c: &Common) -> Result<Scenario> {
    if let Some(n) = c.threads {
        rayon::ThreadPoolBuilder::new().num_threads(n).build_global().ok();
    }
    let mut s = Scenario::load_or_default(c.config.as_deref())?;
    if let Some(seed) = c.seed {
        s.world.seed = seed;
    }
    Ok(s)
}

fn bar(len: usize, what: &str) -> ProgressBar {
    let b = ProgressBar::new(len as u64);
    b.set_style(ProgressStyle::with_template(&format!("{what} {{bar:40}} {{pos}}/{{len}} [{{elapsed_precise}} < {{eta_precise}}] {{per_sec}}")).unwrap());
    b
}

#[derive(Args)]
pub struct ConfigArgs {
    #[command(flatten)]
    pub common: Common,
}

pub fn config(a: ConfigArgs) -> Result<()> {
    let s = setup(&a.common)?;
    print!("{}", s.to_yaml());
    Ok(())
}

#[derive(Args)]
pub struct TrajArgs {
    #[command(flatten)]
    pub common: Common,
    /// Output CSV (default: trajectory.file).
    #[arg(long, short)]
    pub out: Option<PathBuf>,
}

fn synth(s: &Scenario, out: &Path) -> Result<()> {
    let gen = Generator::new(s.world.clone());
    let home = s.world.home.clone().unwrap_or_default();
    let ell = gen.world.ell;
    // ground reference for AGL flights: smooth terrain sampled at ~200 m resolution
    let ground = |lat: f64, lon: f64| -> f64 {
        let t = gen.world.terrain(&terragen::world::Ctx::new(lat, lon, 200.0, &ell));
        if t.water_kind != 0 { t.water.max(t.ground) } else { t.ground }
    };
    let t0 = std::time::Instant::now();
    let recs = dynamics::simulate(&s.trajectory.synth, (home.lat, home.lon), &ell, Some(&ground));
    let note = format!("generated by `terrain traj` with:\n{}", serde_yaml::to_string(&s.trajectory.synth)?);
    dynamics::save_records(out, &recs, &note)?;
    let first = &recs[0].pose;
    let last = &recs[recs.len() - 1].pose;
    eprintln!(
        "wrote {} samples ({:.1} s) to {} in {:.2}s; start {:.5},{:.5} h={:.0} m, end {:.5},{:.5} h={:.0} m",
        recs.len(),
        last.t,
        out.display(),
        t0.elapsed().as_secs_f64(),
        first.geo.lat.to_degrees(),
        first.geo.lon.to_degrees(),
        first.geo.h,
        last.geo.lat.to_degrees(),
        last.geo.lon.to_degrees(),
        last.geo.h
    );
    Ok(())
}

pub fn traj(a: TrajArgs) -> Result<()> {
    let s = setup(&a.common)?;
    let out = a.out.unwrap_or_else(|| s.trajectory.file.clone());
    synth(&s, &out)
}

fn load_poses(s: &Scenario) -> Result<Vec<render::Pose>> {
    let ell = geodesy::Ellipsoid::from_a_invf(s.world.planet.a, s.world.planet.inv_f);
    let p = render::trajectory::load(&s.trajectory.file, &ell).with_context(|| "loading trajectory (run `terrain traj` first?)")?;
    if p.is_empty() {
        bail!("trajectory {} is empty", s.trajectory.file.display());
    }
    Ok(p)
}

fn plan_tiles(s: &Scenario, gen: &Generator) -> Result<BTreeSet<TileId>> {
    let poses = load_poses(s)?;
    let model = s.camera.build()?;
    let t0 = std::time::Instant::now();
    let set = pipeline::plan(s, &poses, Some(gen), model.as_ref());
    let mut per_zoom = std::collections::BTreeMap::new();
    for t in &set {
        *per_zoom.entry(t.z).or_insert(0usize) += 1;
    }
    eprintln!("planned {} tiles in {:.2}s: {:?}", set.len(), t0.elapsed().as_secs_f64(), per_zoom);
    Ok(set)
}

#[derive(Args)]
pub struct PlanArgs {
    #[command(flatten)]
    pub common: Common,
    /// Write the tile list (one `z/x/y` per line).
    #[arg(long, short)]
    pub out: Option<PathBuf>,
}

pub fn plan(a: PlanArgs) -> Result<()> {
    let s = setup(&a.common)?;
    let gen = Generator::new(s.world.clone());
    let set = plan_tiles(&s, &gen)?;
    if let Some(o) = a.out {
        let txt: String = set.iter().map(|t| format!("{}/{}/{}\n", t.z, t.x, t.y)).collect();
        if let Some(p) = o.parent() {
            std::fs::create_dir_all(p).ok();
        }
        std::fs::write(&o, txt)?;
        eprintln!("wrote {}", o.display());
    }
    Ok(())
}

#[derive(Args)]
pub struct GenArgs {
    #[command(flatten)]
    pub common: Common,
    /// Tile list file (`z/x/y` per line). Default: plan from the trajectory.
    #[arg(long)]
    pub tiles: Option<PathBuf>,
    /// Generate a full region instead: lat_min,lon_min,lat_max,lon_max (deg).
    #[arg(long, allow_hyphen_values = true)]
    pub bbox: Option<String>,
    /// Zoom range for --bbox, e.g. 6-14.
    #[arg(long)]
    pub zooms: Option<String>,
    /// Regenerate tiles that already exist.
    #[arg(long)]
    pub force: bool,
}

fn parse_tile_list(p: &Path) -> Result<Vec<TileId>> {
    let mut v = Vec::new();
    for l in std::fs::read_to_string(p)?.lines() {
        let l = l.trim();
        if l.is_empty() || l.starts_with('#') {
            continue;
        }
        let f: Vec<u32> = l.split('/').map(|s| s.trim().parse()).collect::<Result<_, _>>()?;
        if f.len() != 3 {
            bail!("bad tile line {l}");
        }
        v.push(TileId::new(f[0] as u8, f[1], f[2]));
    }
    Ok(v)
}

fn gen_tiles(s: &Scenario, gen: &Generator, tiles: Vec<TileId>, force: bool) -> Result<()> {
    let store = pipeline::open_or_create_store(s, gen)?;
    let b = bar(0, "gen");
    let t0 = std::time::Instant::now();
    let n = pipeline::generate(gen, &store, &tiles, force, &|done, total| {
        b.set_length(total as u64);
        b.set_position(done as u64);
    })?;
    b.finish();
    eprintln!("generated {n} tiles ({} requested) in {:.1}s → {} ({} tiles total)", tiles.len(), t0.elapsed().as_secs_f64(), s.tiles.file.display(), store.len());
    Ok(())
}

pub fn gen(a: GenArgs) -> Result<()> {
    let s = setup(&a.common)?;
    let gen = Generator::new(s.world.clone());
    let tiles: Vec<TileId> = if let Some(t) = &a.tiles {
        parse_tile_list(t)?
    } else if let Some(bb) = &a.bbox {
        let v: Vec<f64> = bb.split(',').map(|x| x.trim().parse()).collect::<Result<_, _>>()?;
        if v.len() != 4 {
            bail!("--bbox lat_min,lon_min,lat_max,lon_max");
        }
        let zr = a.zooms.as_deref().unwrap_or("0-12");
        let (z0, z1) = zr.split_once('-').map(|(a, b)| (a.parse::<u8>(), b.parse::<u8>())).context("--zooms a-b")?;
        let (z0, z1) = (z0?, z1?);
        let b = LatLonBounds { lat_min: v[0].to_radians(), lon_min: v[1].to_radians(), lat_max: v[2].to_radians(), lon_max: v[3].to_radians() };
        (z0..=z1).flat_map(|z| tiles_in_bounds(&b, z)).collect()
    } else {
        plan_tiles(&s, &gen)?.into_iter().collect()
    };
    gen_tiles(&s, &gen, tiles, a.force)
}

#[derive(Args)]
pub struct RenderArgs {
    #[command(flatten)]
    pub common: Common,
    /// Generate missing tiles on the fly (overrides tiles.lazy).
    #[arg(long)]
    pub lazy: bool,
}

fn do_render(s: &Scenario) -> Result<()> {
    let poses = load_poses(s)?;
    let gen = Arc::new(Generator::new(s.world.clone()));
    let store = if s.tiles.lazy {
        pipeline::open_or_create_store(s, &gen)?
    } else {
        TileStore::open(&s.tiles.file).with_context(|| "opening tile store (run `terrain gen` first, or use --lazy)")?
    };
    let store = Arc::new(store);
    let b = bar(0, "render");
    let t0 = std::time::Instant::now();
    pipeline::render_sequence(s, &poses, store, Some(gen), &|done, total| {
        b.set_length(total as u64);
        b.set_position(done as u64);
    })?;
    b.finish();
    if s.imu.enabled && s.output.h5.is_some() {
        let n = pipeline::write_imu(s, &poses, &s.trajectory.file)?;
        eprintln!("imu: {n} samples at {} Hz → {}{}", s.imu.rate_hz, s.output.h5.as_ref().unwrap().display(), s.output.layout.imu_group);
    }
    eprintln!(
        "rendered in {:.1}s → {}{}",
        t0.elapsed().as_secs_f64(),
        if s.output.png { s.output.dir.display().to_string() } else { String::new() },
        s.output.h5.as_ref().map(|p| format!(" + {}", p.display())).unwrap_or_default()
    );
    Ok(())
}

pub fn render(a: RenderArgs) -> Result<()> {
    let mut s = setup(&a.common)?;
    if a.lazy {
        s.tiles.lazy = true;
    }
    do_render(&s)
}

fn do_events(s: &Scenario) -> Result<()> {
    let poses = load_poses(s)?;
    let gen = Arc::new(Generator::new(s.world.clone()));
    let store = if s.tiles.lazy {
        pipeline::open_or_create_store(s, &gen)?
    } else {
        TileStore::open(&s.tiles.file).with_context(|| "opening tile store (run `terrain gen` first, or use --lazy)")?
    };
    let b = ProgressBar::new(1000);
    b.set_style(ProgressStyle::with_template("events {bar:40} {percent}% [{elapsed_precise} < {eta_precise}]").unwrap());
    let t0 = std::time::Instant::now();
    let n = pipeline::render_events(s, &poses, Arc::new(store), Some(gen), &|done, total| {
        b.set_position((1000.0 * done / total.max(1e-9)) as u64);
    })?;
    b.finish();
    let dst = s.events.h5.clone().or(s.output.h5.clone()).unwrap_or_default();
    eprintln!("simulated {n} events in {:.1}s → {}{}", t0.elapsed().as_secs_f64(), dst.display(), s.output.layout.events_group);
    Ok(())
}

pub fn events(a: RenderArgs) -> Result<()> {
    let mut s = setup(&a.common)?;
    if a.lazy {
        s.tiles.lazy = true;
    }
    do_events(&s)
}

#[derive(Args)]
pub struct RunArgs {
    #[command(flatten)]
    pub common: Common,
    /// Re-synthesize the trajectory even if the file exists.
    #[arg(long)]
    pub new_traj: bool,
}

pub fn run(a: RunArgs) -> Result<()> {
    let s = setup(&a.common)?;
    if a.new_traj || !s.trajectory.file.exists() {
        synth(&s, &s.trajectory.file)?;
    }
    let gen = Generator::new(s.world.clone());
    let tiles = plan_tiles(&s, &gen)?;
    gen_tiles(&s, &gen, tiles.into_iter().collect(), false)?;
    drop(gen);
    do_render(&s)?;
    if s.events.enabled {
        do_events(&s)?;
    }
    Ok(())
}

#[derive(Args)]
pub struct InfoArgs {
    pub file: PathBuf,
}

pub fn info(a: InfoArgs) -> Result<()> {
    if let Ok(st) = TileStore::open(&a.file) {
        let m = st.meta();
        println!("tile store {} (seed {}, ellipsoid a={} b={:.6})", a.file.display(), m.seed, m.ellipsoid_a, m.ellipsoid_b);
        println!("layers: {:?}", m.layers.iter().map(|l| l.name()).collect::<Vec<_>>());
        for z in st.zooms() {
            let t = st.tiles_at(z);
            let (mut lo, mut hi) = (f32::MAX, f32::MIN);
            for id in &t {
                if let Some((a, b)) = st.elev_range(*id) {
                    lo = lo.min(a);
                    hi = hi.max(b);
                }
            }
            println!("  z{z:2}: {:6} tiles  elevation {lo:.0} .. {hi:.0} m", t.len());
        }
        return Ok(());
    }
    let f = h5::File::open(&a.file)?;
    use h5::Attrs;
    println!("{} (format {:?})", a.file.display(), f.attr_str("format").unwrap_or_default());
    for name in f.member_names()? {
        if let Ok(ds) = f.dataset(&name) {
            println!("  {name}: {:?}", ds.shape()?);
        } else {
            println!("  {name}/");
        }
    }
    Ok(())
}
