# Type stub of the extension module (bindings/python/src/lib.rs).
import os

__version__: str
TILE_SIZE: int
MAX_ZOOM: int
DEFAULT_MAX_ZOOM: int
GENERATOR_VERSION: int

class World:
    def __init__(self, tiles_file: str | os.PathLike[str], config: str | os.PathLike[str] | None = None, seed: int | None = None) -> None: ...
    def tile(self, z: int, x: int, y: int, layer: str) -> bytearray: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    @property
    def path(self) -> os.PathLike[str] | str: ...
    @property
    def seed(self) -> int: ...
    @property
    def max_zoom(self) -> int: ...

def layers() -> list[tuple[str, str, int, int, str]]: ...
