/*
 * aerialsynth C API: tiles of a procedural world (Web-Mercator XYZ, 256 x 256 pixels), read from
 * its HDF5 tile store and generated (GPU if available, else CPU) and stored when missing.
 *
 * Link with -laerialsynth (libaerialsynth.so / .dylib / aerialsynth.dll, or the static
 * libaerialsynth.a with its system libraries). See bindings/README.md and examples/tile.c.
 *
 * Thread safety: a handle may be used by several threads at once (as_tile); as_close must not
 * run concurrently with other calls on the same handle. as_last_error is per thread.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef AERIALSYNTH_H
#define AERIALSYNTH_H

/* Generated by cbindgen from bindings/c/src/lib.rs: do not edit. Regenerate with AERIALSYNTH_BLESS=1 cargo test -p aerialsynth-capi --test header */

#include <stddef.h>
#include <stdint.h>

/**
 * Number of layers (valid layers are 0 .. AS_LAYER_COUNT - 1).
 */
#define AS_LAYER_COUNT 6

/**
 * Success.
 */
#define AS_OK 0

/**
 * A bad argument: NULL pointer, unknown layer, tile out of range (z above the world's max zoom,
 * x or y >= 2^z).
 */
#define AS_ERR_INVALID_ARGUMENT -1

/**
 * The output buffer is smaller than the layer's tile size (`as_layer_size`).
 */
#define AS_ERR_BUFFER_TOO_SMALL -2

/**
 * Reading, generating or storing the tile failed (see `as_last_error`).
 */
#define AS_ERR_FAILED -3

/**
 * An internal error (a Rust panic, caught at the API boundary; see `as_last_error`).
 */
#define AS_ERR_PANIC -4

/**
 * Width and height of a tile in pixels.
 */
#define AS_TILE_SIZE 256

/**
 * A tile store opened for one world. Opaque; made by `as_open`, freed by `as_close`.
 */
typedef struct as_world as_world;

/**
 * A layer of a tile: one of the `AS_LAYER_*` values.
 */
typedef uint32_t as_layer;

/**
 * Element type of a layer's pixels: one of the `AS_DTYPE_*` values.
 */
typedef uint32_t as_dtype;

/**
 * Pixel format of a layer (`as_layer_describe`).
 */
typedef struct as_layer_info {
  /**
   * Layer name ("rgb", "albedo", "elevation", "normal", "landcover", "emission"); static.
   */
  const char *name;
  /**
   * An `AS_DTYPE_*` value.
   */
  as_dtype dtype;
  /**
   * Channels per pixel: 1 or 3.
   */
  uint32_t channels;
  /**
   * Bytes per channel: 1 or 4.
   */
  uint32_t elem_size;
  /**
   * Bytes of one tile of this layer: 256 * 256 * channels * elem_size.
   */
  size_t size;
} as_layer_info;

/**
 * Satellite look: the surface lit by a fixed sun, with haze. u8 x 3, sRGB.
 */
#define AS_LAYER_RGB 0

/**
 * Unlit surface colour. u8 x 3, sRGB encoded.
 */
#define AS_LAYER_ALBEDO 1

/**
 * DSM (ground, canopy, buildings, water surface) in metres above the WGS84 ellipsoid, at pixel
 * centres. f32 x 1.
 */
#define AS_LAYER_ELEVATION 2

/**
 * Unit surface normal (east, north, up) * 127. i8 x 3.
 */
#define AS_LAYER_NORMAL 3

/**
 * Land-cover class id (0 unknown, 1 ocean, 2 lake, 3 river, 4 beach, 5 sand, 6 rock, 7 snow,
 * 8 grass, 9 shrub, 10 forest, 11 crop, 12 building, 13 road, 14 wetland, 15 tundra, 16 bare,
 * 17 urban). u8 x 1.
 */
#define AS_LAYER_LANDCOVER 4

/**
 * Night-time artificial light: linear radiance = 16 * (v/255)^3. u8 x 3.
 */
#define AS_LAYER_EMISSION 5

/**
 * unsigned 8-bit
 */
#define AS_DTYPE_U8 0

/**
 * signed 8-bit
 */
#define AS_DTYPE_I8 1

/**
 * little-endian IEEE 754 binary32
 */
#define AS_DTYPE_F32 2

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The library version ("0.1.0"); a static string.
 */
const char *as_version(void);

/**
 * The message of the last failed call on this thread ("" if none failed yet). The string is
 * owned by the library and valid until the next failing call on the same thread.
 */
const char *as_last_error(void);

/**
 * Open the tile store `tiles_file` (created, with its directory, if missing) for a world.
 *
 * The world is defined like `terrain -c CONFIG --seed SEED`: `config_yaml` is the path of a
 * scenario YAML (its `world:` section is the world, its `tiles.max_zoom` the zoom limit, default
 * 18; other sections are ignored) or of a bare world config, or NULL for the default world.
 * `seed` >= 0 overrides the config's seed (< 0 keeps it).
 *
 * A store holds one world: a store of another world (or generator version) is refused. A tiles
 * file can be open only once per process: share the handle (it is thread-safe) instead.
 * Returns NULL on error (see `as_last_error`). Close the handle with `as_close`.
 *
 * # Safety
 * `tiles_file` is a NUL-terminated path; `config_yaml` is NULL or a NUL-terminated path.
 */
struct as_world *as_open(const char *tiles_file, const char *config_yaml, int64_t seed);

/**
 * Close a world (flushing its store). NULL is ignored. The handle must not be in use by another
 * thread, and is invalid afterwards.
 *
 * # Safety
 * `w` is NULL or a handle from `as_open` not closed yet.
 */
void as_close(struct as_world *w);

/**
 * Write the pixels of `layer` of tile `z/x/y` to `out`: `as_layer_size(layer)` bytes, row-major,
 * 256 rows (row 0 = north) x 256 columns x channels, little-endian. A tile that is not stored
 * yet is generated (all layers; on the GPU when there is a suitable one, else on the CPU) and
 * stored first.
 *
 * `z` must be at most the world's max zoom, `x` and `y` less than 2^z (XYZ / Web-Mercator
 * scheme, y = 0 at the north edge). A handle can be used from several threads at once.
 * Returns `AS_OK` or a negative `AS_ERR_*` code (see `as_last_error`).
 *
 * # Safety
 * `w` is a handle from `as_open`; `out` points to `out_len` writable bytes.
 */
int as_tile(const struct as_world *w,
            uint32_t z,
            uint32_t x,
            uint32_t y,
            as_layer layer,
            void *out,
            size_t out_len);

/**
 * The highest zoom the world serves (`tiles.max_zoom` of its config, default 18), or -1 if `w`
 * is NULL.
 *
 * # Safety
 * `w` is NULL or a handle from `as_open`.
 */
int as_max_zoom(const struct as_world *w);

/**
 * Bytes of one tile of `layer` (256 * 256 * channels * element size), or 0 for an unknown layer.
 */
size_t as_layer_size(as_layer layer);

/**
 * Describe `layer` into `*info`. Returns `AS_OK` or `AS_ERR_INVALID_ARGUMENT`.
 *
 * # Safety
 * `info` points to a writable `as_layer_info`.
 */
int as_layer_describe(as_layer layer, struct as_layer_info *info);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AERIALSYNTH_H */
