/*
 * aerialsynth C API: tiles of a procedural world (Web-Mercator XYZ, 256 x 256 pixels), read from
 * its HDF5 tile store and generated (GPU if available, else CPU) and stored when missing; camera
 * images of the world rendered from a pose (the renderer of `terrain run`).
 *
 * Link with -laerialsynth (libaerialsynth.so / .dylib / aerialsynth.dll, or the static
 * libaerialsynth.a with its system libraries). See bindings/README.md, examples/tile.c and
 * examples/render.c.
 *
 * Thread safety: a world or camera handle may be used by several threads at once (as_tile,
 * as_render; renders of one camera are serialized); as_close / as_camera_close must not run
 * concurrently with other calls on the same handle. as_last_error is per thread.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef AERIALSYNTH_H
#define AERIALSYNTH_H

/* Generated by cbindgen from bindings/c/src/lib.rs: do not edit. Regenerate with AERIALSYNTH_BLESS=1 cargo test -p aerialsynth-capi --test header */

#include <stddef.h>
#include <stdint.h>

/**
 * Number of layers (valid layers are 0 .. AS_LAYER_COUNT - 1).
 */
#define AS_LAYER_COUNT 6

/**
 * Success.
 */
#define AS_OK 0

/**
 * A bad argument: NULL pointer, unknown layer, tile out of range (z above the world's max zoom,
 * x or y >= 2^z).
 */
#define AS_ERR_INVALID_ARGUMENT -1

/**
 * The output buffer is smaller than the layer's tile size (`as_layer_size`).
 */
#define AS_ERR_BUFFER_TOO_SMALL -2

/**
 * Reading, generating or storing the tile failed (see `as_last_error`).
 */
#define AS_ERR_FAILED -3

/**
 * An internal error (a Rust panic, caught at the API boundary; see `as_last_error`).
 */
#define AS_ERR_PANIC -4

/**
 * Width and height of a tile in pixels.
 */
#define AS_TILE_SIZE 256

/**
 * A camera over a world, rendering images from poses. Opaque; made by `as_camera_open` or
 * `as_camera_pinhole`, freed by `as_camera_close`.
 */
typedef struct as_camera as_camera;

/**
 * A tile store opened for one world. Opaque; made by `as_open`, freed by `as_close`.
 */
typedef struct as_world as_world;

/**
 * A layer of a tile: one of the `AS_LAYER_*` values.
 */
typedef uint32_t as_layer;

/**
 * Where a camera renders: one of the `AS_BACKEND_*` values.
 */
typedef uint32_t as_backend;

/**
 * How a pinhole camera sits on the body: one of the `AS_MOUNT_*` values.
 */
typedef uint32_t as_mount;

/**
 * Position and body attitude of a render.
 *
 * Position: geodetic latitude and longitude (degrees) and height above the WGS84 ellipsoid
 * (metres). Attitude: aerospace Z-Y-X Euler angles (degrees) of the body (x forward, y right,
 * z down) in the local north-east-down frame: yaw = heading clockwise from north, pitch nose-up
 * positive, roll right-wing-down positive. The camera sits on the body by its mount (the
 * scenario camera's `extrinsics`, or `as_mount` for a pinhole camera).
 */
typedef struct as_pose {
  double lat_deg;
  double lon_deg;
  double height_m;
  double roll_deg;
  double pitch_deg;
  double yaw_deg;
} as_pose;

/**
 * Element type of a layer's pixels: one of the `AS_DTYPE_*` values.
 */
typedef uint32_t as_dtype;

/**
 * Pixel format of a layer (`as_layer_describe`).
 */
typedef struct as_layer_info {
  /**
   * Layer name ("rgb", "albedo", "elevation", "normal", "landcover", "emission"); static.
   */
  const char *name;
  /**
   * An `AS_DTYPE_*` value.
   */
  as_dtype dtype;
  /**
   * Channels per pixel: 1 or 3.
   */
  uint32_t channels;
  /**
   * Bytes per channel: 1 or 4.
   */
  uint32_t elem_size;
  /**
   * Bytes of one tile of this layer: 256 * 256 * channels * elem_size.
   */
  size_t size;
} as_layer_info;

/**
 * Satellite look: the surface lit by a fixed sun, with haze. u8 x 3, sRGB.
 */
#define AS_LAYER_RGB 0

/**
 * Unlit surface colour. u8 x 3, sRGB encoded.
 */
#define AS_LAYER_ALBEDO 1

/**
 * DSM (ground, canopy, buildings, water surface) in metres above the WGS84 ellipsoid, at pixel
 * centres. f32 x 1.
 */
#define AS_LAYER_ELEVATION 2

/**
 * Unit surface normal (east, north, up) * 127. i8 x 3.
 */
#define AS_LAYER_NORMAL 3

/**
 * Land-cover class id (0 unknown, 1 ocean, 2 lake, 3 river, 4 beach, 5 sand, 6 rock, 7 snow,
 * 8 grass, 9 shrub, 10 forest, 11 crop, 12 building, 13 road, 14 wetland, 15 tundra, 16 bare,
 * 17 urban). u8 x 1.
 */
#define AS_LAYER_LANDCOVER 4

/**
 * Night-time artificial light: linear radiance = 16 * (v/255)^3. u8 x 3.
 */
#define AS_LAYER_EMISSION 5

/**
 * unsigned 8-bit
 */
#define AS_DTYPE_U8 0

/**
 * signed 8-bit
 */
#define AS_DTYPE_I8 1

/**
 * little-endian IEEE 754 binary32
 */
#define AS_DTYPE_F32 2

/**
 * The scenario's `render.backend` (`AS_BACKEND_AUTO` without a scenario).
 */
#define AS_BACKEND_DEFAULT 0

/**
 * The GPU when there is a usable one (that can take the camera model), else the CPU.
 */
#define AS_BACKEND_AUTO 1

/**
 * The CPU reference renderer.
 */
#define AS_BACKEND_CPU 2

/**
 * The GPU: opening the camera fails without a usable GPU.
 */
#define AS_BACKEND_GPU 3

/**
 * Optical axis = body forward, image top = body up: the pose's angles are the camera's own (yaw
 * = heading of the optical axis, pitch = its elevation, negative looks down).
 */
#define AS_MOUNT_FORWARD 0

/**
 * Optical axis = body down, image top = body forward (the scenario default mount): a level
 * pose looks straight down.
 */
#define AS_MOUNT_NADIR 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The library version ("0.1.0"); a static string.
 */
const char *as_version(void);

/**
 * The message of the last failed call on this thread ("" if none failed yet). The string is
 * owned by the library and valid until the next failing call on the same thread.
 */
const char *as_last_error(void);

/**
 * Open the tile store `tiles_file` (created, with its directory, if missing) for a world.
 *
 * The world is defined like `terrain -c CONFIG --seed SEED`: `config_yaml` is the path of a
 * scenario YAML (its `world:` section is the world, its `tiles.max_zoom` the zoom limit, default
 * 18; other sections are ignored) or of a bare world config, or NULL for the default world.
 * `seed` >= 0 overrides the config's seed (< 0 keeps it).
 *
 * A store holds one world: a store of another world (or generator version) is refused. A tiles
 * file can be open only once per process: share the handle (it is thread-safe) instead.
 * Returns NULL on error (see `as_last_error`). Close the handle with `as_close`.
 *
 * # Safety
 * `tiles_file` is a NUL-terminated path; `config_yaml` is NULL or a NUL-terminated path.
 */
struct as_world *as_open(const char *tiles_file, const char *config_yaml, int64_t seed);

/**
 * Close a world (flushing its store). NULL is ignored. The handle must not be in use by another
 * thread, and is invalid afterwards. Cameras of the world stay usable: the store is closed when
 * the world and all its cameras are closed.
 *
 * # Safety
 * `w` is NULL or a handle from `as_open` not closed yet.
 */
void as_close(struct as_world *w);

/**
 * Write the pixels of `layer` of tile `z/x/y` to `out`: `as_layer_size(layer)` bytes, row-major,
 * 256 rows (row 0 = north) x 256 columns x channels, little-endian. A tile that is not stored
 * yet is generated (all layers; on the GPU when there is a suitable one, else on the CPU) and
 * stored first.
 *
 * `z` must be at most the world's max zoom, `x` and `y` less than 2^z (XYZ / Web-Mercator
 * scheme, y = 0 at the north edge). A handle can be used from several threads at once.
 * Returns `AS_OK` or a negative `AS_ERR_*` code (see `as_last_error`).
 *
 * # Safety
 * `w` is a handle from `as_open`; `out` points to `out_len` writable bytes.
 */
int as_tile(const struct as_world *w,
            uint32_t z,
            uint32_t x,
            uint32_t y,
            as_layer layer,
            void *out,
            size_t out_len);

/**
 * The highest zoom the world serves (`tiles.max_zoom` of its config, default 18), or -1 if `w`
 * is NULL.
 *
 * # Safety
 * `w` is NULL or a handle from `as_open`.
 */
int as_max_zoom(const struct as_world *w);

/**
 * The DSM height (ground, canopy, buildings, water surface; metres above the WGS84 ellipsoid) at
 * latitude / longitude `lat_deg`, `lon_deg` into `*height_m`: about what the tiles of the max
 * zoom hold there (evaluated by the generator; no tile is made). For heights above ground.
 * Returns `AS_OK` or a negative `AS_ERR_*` code.
 *
 * # Safety
 * `w` is a handle from `as_open`; `height_m` points to a writable double.
 */
int as_surface_height(const struct as_world *w, double lat_deg, double lon_deg, double *height_m);

/**
 * A camera of a scenario over world `w`.
 *
 * `scenario_yaml` is the path of a scenario YAML (as for `terrain run`) or NULL for the default
 * settings: its `render` section (backend, supersample, shading, lighting, atmosphere, ...),
 * `tiles` zoom range and cache size and `cameras` are used; its `world` section is ignored (the
 * world is `w`'s). `camera` picks one of its `cameras` by HDF5 path ("/cam0") or index ("0");
 * NULL is the first one (the default camera, 640 x 512 with a 70 degree field of view on a nadir
 * mount, when there is none). `backend` overrides `render.backend` (`AS_BACKEND_DEFAULT` keeps
 * it).
 *
 * The camera keeps the world's store open (`as_close` of the world may come first). Returns NULL
 * on error (see `as_last_error`). Close the camera with `as_camera_close`.
 *
 * # Safety
 * `w` is a handle from `as_open`; `scenario_yaml` and `camera` are NULL or NUL-terminated.
 */
struct as_camera *as_camera_open(const struct as_world *w,
                                 const char *scenario_yaml,
                                 const char *camera,
                                 as_backend backend);

/**
 * A distortion-free pinhole camera over world `w`: `width` x `height` pixels, horizontal field
 * of view `hfov_deg` (0 < hfov < 180), principal point at the image centre, mounted by `mount`
 * (`AS_MOUNT_FORWARD` or `AS_MOUNT_NADIR`), with the default render settings; `backend`
 * (`AS_BACKEND_DEFAULT` = `AS_BACKEND_AUTO`).
 *
 * The camera keeps the world's store open. Returns NULL on error (see `as_last_error`). Close
 * the camera with `as_camera_close`.
 *
 * # Safety
 * `w` is a handle from `as_open`.
 */
struct as_camera *as_camera_pinhole(const struct as_world *w,
                                    uint32_t width,
                                    uint32_t height,
                                    double hfov_deg,
                                    as_mount mount,
                                    as_backend backend);

/**
 * The image size of camera `c` into `*width` and `*height` (either may be NULL). Returns `AS_OK`
 * or `AS_ERR_INVALID_ARGUMENT` (`c` is NULL).
 *
 * # Safety
 * `c` is NULL or a camera handle; `width` and `height` are NULL or point to writable `uint32_t`s.
 */
int as_camera_size(const struct as_camera *c, uint32_t *width, uint32_t *height);

/**
 * The backend camera `c` renders on: `AS_BACKEND_CPU` or `AS_BACKEND_GPU` (auto resolved), or
 * `AS_ERR_INVALID_ARGUMENT` if `c` is NULL.
 *
 * # Safety
 * `c` is NULL or a camera handle.
 */
int as_camera_backend(const struct as_camera *c);

/**
 * Render a frame of camera `c` from `pose` at `unix_time` (UTC, Unix seconds; NAN: the
 * scenario's lighting time). Tiles the view needs are read from the store, or generated and
 * stored when missing. Only the images whose buffer is not NULL are made; each `*_len` is the
 * buffer's length in elements and must be at least:
 *
 * - `rgb`: width * height * 3 bytes, row-major (row 0 = image top), sRGB after the camera
 *   sensor model (auto exposure converged on the frame, optics, noise, tone curve; no motion
 *   blur). The noise is deterministic: the same camera, pose and time give the same image.
 * - `depth`: width * height floats, metres: the z-depth along the optical axis (OpenCV camera
 *   frame: x right, y down, z forward), or the range along the pixel ray when the scenario
 *   camera's `depth.kind` is `range`; +infinity where there is no terrain (sky).
 * - `landcover`: width * height class ids (as `AS_LAYER_LANDCOVER`), 255 = sky.
 *
 * The time places the sun, moon and stars (as the lighting `clock` mode at that instant).
 * Renders of one camera are serialized; different cameras render concurrently. Returns `AS_OK`
 * or a negative `AS_ERR_*` code (`AS_ERR_INVALID_ARGUMENT`: a NULL camera or pose, a pose out
 * of range (|lat| > 90, non-finite values), a non-finite time; `AS_ERR_BUFFER_TOO_SMALL`).
 *
 * # Safety
 * `c` is a camera handle; `pose` points to an `as_pose`; each buffer is NULL or points to
 * `*_len` writable elements.
 */
int as_render(const struct as_camera *c,
              const struct as_pose *pose,
              double unix_time,
              uint8_t *rgb,
              size_t rgb_len,
              float *depth,
              size_t depth_len,
              uint8_t *landcover,
              size_t landcover_len);

/**
 * Close a camera. NULL is ignored. The handle must not be in use by another thread, and is
 * invalid afterwards.
 *
 * # Safety
 * `c` is NULL or a camera handle not closed yet.
 */
void as_camera_close(struct as_camera *c);

/**
 * Bytes of one tile of `layer` (256 * 256 * channels * element size), or 0 for an unknown layer.
 */
size_t as_layer_size(as_layer layer);

/**
 * Describe `layer` into `*info`. Returns `AS_OK` or `AS_ERR_INVALID_ARGUMENT`.
 *
 * # Safety
 * `info` points to a writable `as_layer_info`.
 */
int as_layer_describe(as_layer layer, struct as_layer_info *info);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AERIALSYNTH_H */
