//! `terrain view`: one window, two views of the scenario's world, flown in realtime.
//!
//! * **Map:** the tile store as a globe (its own light shader): browse the planet, see what is
//!   stored, generate as you go. Orbit, or fly.
//! * **Camera:** a scenario camera rendered by the dataset renderer and sensor, live
//!   ([`camera`]): what a dataset frame from that pose and time looks like.
//!
//! Both views share the flight (free flight or plane, [`fly`]) and the tile service ([`tiles`]):
//! the base levels (z0..=`--base-zoom`) are completed on start, and with generation on, the
//! tiles the view wants are generated and stored in the background.

mod camera;
mod fly;
mod globe;
mod snapshot;
mod tiles;

use anyhow::Result;
use camera::CameraView;
use eframe::{egui, egui_wgpu, wgpu};
use fly::{FlyCam, FlyInput, FlyMode};
use geodesy::tiles::TileId;
use glam::{DVec2, DVec3};
use globe::{CamFrame, Camera, Globe, Mode, Settings};
use render::scenario::{CameraSpec, Scenario};
use std::path::PathBuf;
use std::sync::atomic::Ordering;
use std::sync::Arc;
use std::time::Instant;
use terragen::Generator;
use tiles::Service;
use tilestore::TileStore;

/// Options of `terrain view`.
#[derive(clap::Args, Clone, Debug)]
pub struct ViewOptions {
    /// Open the camera view (the dataset renderer) instead of the map.
    #[arg(long, help_heading = "View")]
    pub camera_view: bool,
    /// Start flying (free or plane) instead of orbiting the planet.
    #[arg(long, value_parser = ["free", "plane"], help_heading = "View")]
    pub fly: Option<String>,
    /// Start at lat,lon (deg),height above the ground (m) (default: the world's home; flying
    /// 600 m up).
    #[arg(long, allow_hyphen_values = true, help_heading = "View")]
    pub start: Option<String>,

    /// Show stored tiles only (by default the tiles the view wants are generated and stored).
    #[arg(long, help_heading = "Tiles")]
    pub no_generate: bool,
    /// Deepest level generated (default: tiles.max_zoom).
    #[arg(long, help_heading = "Tiles")]
    pub max_zoom: Option<u8>,
    /// Levels 0..=this are completed for the whole planet on start.
    #[arg(long, default_value_t = 4, help_heading = "Tiles")]
    pub base_zoom: u8,

    /// The scenario camera (HDF5 path; default: the first with `rgb`, else a
    /// 960 × 540 forward camera).
    #[arg(long, help_heading = "Camera view")]
    pub camera: Option<String>,
    /// Render at this fraction of the camera's resolution (default: at most 960
    /// px wide; pinhole-type models).
    #[arg(long, help_heading = "Camera view")]
    pub scale: Option<f64>,
    /// Supersampling per axis.
    #[arg(long, default_value_t = 1, help_heading = "Camera view")]
    pub supersample: u32,

    /// Relief exaggeration at start.
    #[arg(long, default_value_t = 1.0, help_heading = "Map")]
    pub exag: f32,
    /// Shading at start.
    #[arg(long, default_value = "surface", value_parser = ["surface", "elevation", "landcover", "relief"], help_heading = "Map")]
    pub mode: String,
    /// Tiles kept on the GPU (768 KB each; capped by the GPU's texture array limit).
    #[arg(long, default_value_t = 1536, help_heading = "Map")]
    pub gpu_tiles: u32,

    /// Render one map view without a window into this PNG (once its tiles are in) and exit.
    #[arg(long, help_heading = "Snapshot and recording (headless)")]
    pub snapshot: Option<PathBuf>,
    /// View: lat,lon (deg),distance (km),heading,tilt (deg) of the orbit camera, or
    /// `fly:lat,lon,height above ground (m),heading,pitch (deg)`.
    #[arg(long, default_value = "20,10,16000,0,0", allow_hyphen_values = true, help_heading = "Snapshot and recording (headless)")]
    pub view: String,
    /// Longest wait (s) for the view's tiles.
    #[arg(long, default_value_t = 600.0, help_heading = "Snapshot and recording (headless)")]
    pub wait: f64,
    /// Size, WxH.
    #[arg(long, default_value = "1280x800", help_heading = "Snapshot and recording (headless)")]
    pub size: String,
    /// Record a keyframed map flight (--path) into DIR/frame_00000.png, … (headless).
    #[arg(long, value_name = "DIR", requires = "path", help_heading = "Snapshot and recording (headless)")]
    pub record: Option<PathBuf>,
    /// The flight of --record: YAML `keys:` [{t, lat, lon, km, heading, tilt, exag, fov}] and
    /// `look:` [{t, mode, borders, fade}] (docs/viewer.md).
    #[arg(long, help_heading = "Snapshot and recording (headless)")]
    pub path: Option<PathBuf>,
    /// Frames per second of --record.
    #[arg(long, default_value_t = 25.0, help_heading = "Snapshot and recording (headless)")]
    pub fps: f64,
}

/// View the world of `scn` (its tiles in `store`, generated by `gen`).
pub fn run(scn: Scenario, store: Arc<TileStore>, gen: Arc<Generator>, mut opts: ViewOptions) -> Result<()> {
    opts.max_zoom.get_or_insert(scn.tiles.max_zoom);
    if let Some(out) = opts.snapshot.clone() {
        return snapshot::snapshot(&opts, store, gen, &out);
    }
    if let (Some(dir), Some(path)) = (opts.record.clone(), opts.path.clone()) {
        return snapshot::record(&opts, store, gen, &dir, &path, opts.fps);
    }
    let spec = camera::pick_camera(&scn, opts.camera.as_deref())?;
    eprintln!("view: store {} ({} tiles), seed {}, camera {}", store.path().display(), store.len(), gen.config().seed, spec.path);
    let mut setup = egui_wgpu::WgpuSetupCreateNew::without_display_handle();
    // texture arrays of hundreds of tiles: the adapter's own limits, not the portable defaults
    setup.device_descriptor = Arc::new(|adapter: &wgpu::Adapter| wgpu::DeviceDescriptor { label: Some("viewer"), required_limits: adapter.limits(), ..Default::default() });
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default().with_inner_size([1500.0, 950.0]).with_title("terrain view"),
        wgpu_options: egui_wgpu::WgpuConfiguration { wgpu_setup: egui_wgpu::WgpuSetup::CreateNew(setup), ..Default::default() },
        ..Default::default()
    };
    eframe::run_native("terrain view", options, Box::new(move |cc| Ok(Box::new(App::new(cc, scn, spec, opts, store, gen)?)))).map_err(|e| anyhow::anyhow!("{e}"))
}

pub(crate) fn base_tiles(base_zoom: u8) -> Vec<TileId> {
    (0..=base_zoom).flat_map(|z| (0..1u32 << z).flat_map(move |y| (0..1u32 << z).map(move |x| TileId::new(z, x, y)))).collect()
}

pub(crate) fn parse_mode(m: &str) -> Mode {
    match m {
        "elevation" => Mode::Elevation,
        "landcover" => Mode::Landcover,
        "relief" => Mode::Relief,
        _ => Mode::Albedo,
    }
}

pub(crate) fn map_settings(o: &ViewOptions) -> Settings {
    Settings {
        exaggeration: o.exag,
        mode: parse_mode(&o.mode),
        borders: false,
        lod_bias: 1.0,
        dynamic: !o.no_generate,
        gen_max_zoom: o.max_zoom.unwrap_or(17),
        view_max_zoom: 20,
        base_zoom: o.base_zoom,
        sun_follows_view: true,
        sun_lat: 15.0,
        sun_lon: 30.0,
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Tab {
    Map,
    Camera,
}

/// How the map view is driven (the camera view always flies).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Nav {
    Orbit,
    Free,
    Plane,
}

struct App {
    tab: Tab,
    nav: Nav,
    /// the flying body, shared by both views
    fly: Option<FlyCam>,
    /// keep the body this high above the ground (as finer tiles refine it) until the first input
    spawn_agl: Option<f64>,
    orbit: Camera,
    globe: Globe,
    s: Settings,
    svc: Arc<Service>,
    /// started on first use
    camview: Option<CameraView>,
    scn: Scenario,
    spec: CameraSpec,
    scale: f64,
    supersample: u32,
    store_path: PathBuf,
    home: (f64, f64),
    last_cf: Option<CamFrame>,
    agl: f64,
    eye_alt: f64,
    hover: Option<(f64, f64)>,
    counts: Vec<(u8, usize)>,
    counts_at: Instant,
    rate: f64,
    rate_mark: (Instant, u64),
    frame_ms: f64,
    started: Instant,
    last_frame: Instant,
    error: Option<String>,
}

impl App {
    fn new(cc: &eframe::CreationContext<'_>, scn: Scenario, spec: CameraSpec, opts: ViewOptions, store: Arc<TileStore>, gen: Arc<Generator>) -> Result<App, Box<dyn std::error::Error + Send + Sync>> {
        let rs = cc.wgpu_render_state.as_ref().ok_or("wgpu is not available")?;
        let ell = gen.world.ell;
        let home = gen.config().home.as_ref().map(|h| (h.lat.to_radians(), h.lon.to_radians())).unwrap_or((20f64.to_radians(), 10f64.to_radians()));
        let start = match &opts.start {
            Some(s) => {
                let v: Vec<f64> = s.split(',').map(|x| x.trim().parse()).collect::<Result<_, _>>().map_err(|_| "--start lat,lon,agl")?;
                if v.len() != 3 {
                    return Err("--start lat,lon,agl".into());
                }
                Some((v[0].to_radians(), v[1].to_radians(), v[2]))
            }
            None => None,
        };
        let (lat, lon) = start.map(|s| (s.0, s.1)).unwrap_or(home);
        let flying = opts.fly.is_some() || opts.camera_view;
        let fly = flying.then(|| {
            let p = geodesy::geodetic2ecef(geodesy::Geodetic { lat, lon, h: 600.0 }, &ell);
            let mode = if opts.fly.as_deref() == Some("plane") { FlyMode::Plane } else { FlyMode::Free };
            let mut f = FlyCam::at(p, DVec3::X, &ell, 50f64.to_radians(), mode);
            (f.heading, f.pitch, f.speed) = (0.0, if mode == FlyMode::Plane { 0.0 } else { -0.15 }, 60.0);
            f
        });
        let nav = match (opts.fly.as_deref(), flying) {
            (Some("plane"), _) => Nav::Plane,
            (_, true) => Nav::Free,
            _ => Nav::Orbit,
        };
        let ctx = cc.egui_ctx.clone();
        let batch = (rayon::current_num_threads() / 2).max(1);
        let store_path = store.path().to_path_buf();
        let svc = Arc::new(Service::start(store, gen, base_tiles(opts.base_zoom), batch, move || ctx.request_repaint()));
        let scale = opts.scale.unwrap_or((960.0 / spec.intrinsics.width as f64).min(1.0));
        Ok(App {
            tab: if opts.camera_view { Tab::Camera } else { Tab::Map },
            nav,
            fly,
            spawn_agl: flying.then(|| start.map(|s| s.2).unwrap_or(600.0)),
            orbit: Camera { lat, lon, dist: if start.is_some() { 40_000.0 } else { 2.6 * ell.a }, heading: 0.0, tilt: 0.0, fov_y: 40f64.to_radians(), target_h: 0.0 },
            globe: Globe::new(&rs.device, &rs.queue, ell, opts.gpu_tiles),
            s: map_settings(&opts),
            svc,
            camview: None,
            scn,
            spec,
            scale,
            supersample: opts.supersample,
            store_path,
            home,
            last_cf: None,
            agl: 0.0,
            eye_alt: 0.0,
            hover: None,
            counts: Vec::new(),
            counts_at: Instant::now() - std::time::Duration::from_secs(10),
            rate: 0.0,
            rate_mark: (Instant::now(), 0),
            frame_ms: 0.0,
            started: Instant::now(),
            last_frame: Instant::now(),
            error: None,
        })
    }

    fn ell(&self) -> geodesy::Ellipsoid {
        self.globe.ellipsoid()
    }

    /// Make sure there is a flying body, starting it where the map view is.
    fn ensure_fly(&mut self, mode: FlyMode) {
        let ell = self.ell();
        match &mut self.fly {
            Some(f) => f.mode = mode,
            None => {
                let mut f = match &self.last_cf {
                    // from the current view, if it is near the ground; else 600 m over its target
                    Some(cf) if geodesy::ecef2geodetic(cf.eye, &ell).h < 50_000.0 => FlyCam::at(cf.eye, cf.dir, &ell, 50f64.to_radians(), mode),
                    _ => {
                        let p = geodesy::geodetic2ecef(geodesy::Geodetic { lat: self.orbit.lat, lon: self.orbit.lon, h: 600.0 }, &ell);
                        let mut f = FlyCam::at(p, DVec3::X, &ell, 50f64.to_radians(), mode);
                        (f.heading, f.pitch, f.speed) = (self.orbit.heading, -0.15, 60.0);
                        self.spawn_agl = Some(600.0);
                        f
                    }
                };
                if mode == FlyMode::Plane {
                    f.pitch = f.pitch.clamp(-0.3, 0.3);
                }
                self.fly = Some(f);
            }
        }
        if let Some(f) = &mut self.fly {
            if mode == FlyMode::Plane {
                f.speed = f.speed.clamp(30.0, 300.0);
            }
        }
    }

    fn set_nav(&mut self, nav: Nav) {
        match nav {
            Nav::Orbit => {
                if let Some(f) = self.fly.take() {
                    // orbit the ground point under the body, from its height
                    let g = f.geodetic(&self.ell());
                    (self.orbit.lat, self.orbit.lon) = (g.lat, g.lon);
                    self.orbit.dist = self.agl.max(150.0);
                    (self.orbit.heading, self.orbit.tilt) = (f.heading, 0.0);
                }
                if self.tab == Tab::Camera {
                    return; // the camera view always flies
                }
            }
            Nav::Free => self.ensure_fly(FlyMode::Free),
            Nav::Plane => self.ensure_fly(FlyMode::Plane),
        }
        self.nav = nav;
    }

    fn set_tab(&mut self, tab: Tab) {
        if tab == Tab::Camera && self.nav == Nav::Orbit {
            self.set_nav(Nav::Free);
        }
        if tab == Tab::Map {
            if let Some(c) = &self.camview {
                c.pause();
            }
        }
        self.tab = tab;
    }

    fn top_bar(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            let mut tab = self.tab;
            ui.selectable_value(&mut tab, Tab::Map, egui::RichText::new("Map").strong()).on_hover_text("the tile store on a globe (M)");
            ui.selectable_value(&mut tab, Tab::Camera, egui::RichText::new("Camera").strong()).on_hover_text("the scenario camera through the dataset renderer (M)");
            if tab != self.tab {
                self.set_tab(tab);
            }
            ui.separator();
            let mut nav = self.nav;
            ui.add_enabled_ui(self.tab == Tab::Map, |ui| {
                ui.selectable_value(&mut nav, Nav::Orbit, "Orbit");
            });
            ui.selectable_value(&mut nav, Nav::Free, "Free flight");
            ui.selectable_value(&mut nav, Nav::Plane, "Plane");
            if nav != self.nav {
                self.set_nav(nav);
            }
            if let (Some(f), true) = (&mut self.fly, self.nav != Nav::Orbit) {
                let mut kmh = f.speed * 3.6;
                ui.add(egui::Slider::new(&mut kmh, 5.0..=200_000.0).logarithmic(true).suffix(" km/h"));
                f.speed = kmh / 3.6;
            }
            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                let st = self.svc.stats();
                let busy = st.gen_busy.load(Ordering::Relaxed);
                let fps = match (self.tab, &self.camview) {
                    (Tab::Camera, Some(c)) => format!("{:.0} frames/s", c.fps()),
                    _ => format!("{:.0} ms", self.frame_ms),
                };
                ui.label(egui::RichText::new(fps).small().weak());
                if busy > 0 {
                    ui.label(egui::RichText::new(format!("generating · {:.1} tiles/s", self.rate)).small());
                }
            });
        });
    }

    fn side_panel(&mut self, ui: &mut egui::Ui) {
        ui.add_space(4.0);
        ui.label(egui::RichText::new(format!("seed {} · {}", self.svc.gen.config().seed, self.store_path.display())).small().weak());
        if let Some(e) = &self.error {
            ui.colored_label(egui::Color32::from_rgb(230, 120, 90), e);
        }
        ui.separator();
        match self.tab {
            Tab::Map => self.map_section(ui),
            Tab::Camera => match &mut self.camview {
                Some(c) => c.panel(ui),
                None => {
                    ui.label("starting the camera view…");
                }
            },
        }
        ui.separator();
        self.tiles_section(ui);
        ui.separator();
        egui::CollapsingHeader::new("Keys").default_open(false).show(ui, |ui| {
            ui.label(
                egui::RichText::new(
                    "M  map / camera     F  next flight mode\n\
                     Free flight: WASD · Space/C up/down · drag: look\n  scroll: speed · Shift ×5 · Ctrl ×0.2\n\
                     Plane: W/S nose down/up · A/D roll · Q/E rudder\n  Shift/Ctrl throttle · drag: look\n\
                     Orbit (map): drag: move · right drag: turn/tilt\n  scroll: zoom · double click: fly there",
                )
                .small()
                .monospace(),
            );
        });
    }

    fn map_section(&mut self, ui: &mut egui::Ui) {
        ui.horizontal_wrapped(|ui| {
            ui.selectable_value(&mut self.s.mode, Mode::Albedo, "Surface");
            ui.selectable_value(&mut self.s.mode, Mode::Elevation, "Elevation");
            ui.selectable_value(&mut self.s.mode, Mode::Landcover, "Land cover");
            ui.selectable_value(&mut self.s.mode, Mode::Relief, "Relief");
        });
        ui.add(egui::Slider::new(&mut self.s.exaggeration, 1.0..=100.0).logarithmic(true).text("relief ×"));
        egui::CollapsingHeader::new("Display").default_open(false).show(ui, |ui| {
            ui.add(egui::Slider::new(&mut self.s.lod_bias, 0.5..=4.0).text("pixels per texel"));
            ui.add(egui::Slider::new(&mut self.s.view_max_zoom, 0..=22).text("finest level"));
            ui.checkbox(&mut self.s.borders, "Tile borders (coloured by level)");
            ui.checkbox(&mut self.s.sun_follows_view, "Light from the upper left");
            if !self.s.sun_follows_view {
                ui.add(egui::Slider::new(&mut self.s.sun_lon, -180.0..=180.0).text("sun longitude"));
                ui.add(egui::Slider::new(&mut self.s.sun_lat, -23.44..=23.44).text("sun latitude"));
            }
            let g = &self.globe.stats;
            ui.label(egui::RichText::new(format!("patches {} · finest z{} · GPU tiles {} / {}", g.drawn, g.max_zoom_drawn, g.resident, g.capacity)).small().weak());
        });
        if self.nav == Nav::Orbit {
            ui.horizontal_wrapped(|ui| {
                if ui.button("Whole planet").clicked() {
                    (self.orbit.dist, self.orbit.tilt) = (2.6 * self.ell().a, 0.0);
                }
                if ui.button("Home").clicked() {
                    (self.orbit.lat, self.orbit.lon, self.orbit.dist) = (self.home.0, self.home.1, 40_000.0);
                }
                if ui.button("North up").clicked() {
                    self.orbit.heading = 0.0;
                }
                if ui.button("Top down").clicked() {
                    self.orbit.tilt = 0.0;
                }
            });
            ui.label(egui::RichText::new(format!("{:.4}°, {:.4}° · {} up", self.orbit.lat.to_degrees(), self.orbit.lon.to_degrees(), fmt_dist(self.eye_alt))).small().monospace());
            if let Some((la, lo)) = self.hover {
                ui.label(egui::RichText::new(format!("cursor {:.4}°, {:.4}°", la.to_degrees(), lo.to_degrees())).small().weak());
            }
        }
    }

    fn tiles_section(&mut self, ui: &mut egui::Ui) {
        let st = self.svc.stats();
        ui.checkbox(&mut self.s.dynamic, "Generate missing tiles").on_hover_text("generate the tiles the view wants and store them");
        let generated = st.generated.load(Ordering::Relaxed);
        let dt = self.rate_mark.0.elapsed().as_secs_f64();
        if dt > 1.0 {
            self.rate = 0.5 * self.rate + 0.5 * (generated - self.rate_mark.1) as f64 / dt;
            self.rate_mark = (Instant::now(), generated);
        }
        let (bt, bd) = (st.base_total.load(Ordering::Relaxed), st.base_done.load(Ordering::Relaxed));
        if bt > 0 && bd < bt {
            ui.add(egui::ProgressBar::new(bd as f32 / bt as f32).text(format!("base levels z0–z{}: {bd} / {bt}", self.s.base_zoom)));
        }
        let errors = st.errors.load(Ordering::Relaxed);
        if errors > 0 {
            ui.colored_label(egui::Color32::from_rgb(230, 120, 90), format!("{errors} tile errors (see the terminal)"));
        }
        egui::CollapsingHeader::new(format!("Tiles · {} generated", generated)).default_open(false).show(ui, |ui| {
            ui.add_enabled(self.s.dynamic, egui::Slider::new(&mut self.s.gen_max_zoom, self.s.base_zoom..=19).text("deepest level"));
            ui.label(egui::RichText::new(format!("{:.1} tiles/s · {} loaded · {} in flight", self.rate, st.loaded.load(Ordering::Relaxed), self.svc.in_flight())).small().weak());
            if self.counts_at.elapsed().as_secs_f64() > 1.0 {
                self.counts = self.svc.store.zooms().into_iter().map(|z| (z, self.svc.store.tiles_at(z).len())).collect();
                self.counts_at = Instant::now();
            }
            egui::Grid::new("counts").num_columns(2).spacing([14.0, 2.0]).show(ui, |ui| {
                for (k, (z, n)) in self.counts.iter().enumerate() {
                    ui.monospace(format!("z{z:<2} {n:>7}"));
                    if k % 2 == 1 {
                        ui.end_row();
                    }
                }
            });
        });
    }

    /// The flight inputs of this frame.
    fn fly_input(ui: &egui::Ui, resp: &egui::Response, typing: bool, scroll_speed: bool) -> FlyInput {
        let key = |k: egui::Key| if !typing && ui.input(|i| i.key_down(k)) { 1.0 } else { 0.0 };
        let d = if resp.dragged() { resp.drag_delta() } else { egui::Vec2::ZERO };
        FlyInput {
            forward: key(egui::Key::W) - key(egui::Key::S),
            right: key(egui::Key::D) - key(egui::Key::A),
            up: key(egui::Key::Space) - key(egui::Key::C),
            yaw: key(egui::Key::E) - key(egui::Key::Q),
            boost: ui.input(|i| i.modifiers.shift),
            slow: ui.input(|i| i.modifiers.ctrl),
            look_yaw: d.x as f64 * 0.003,
            look_pitch: -d.y as f64 * 0.003,
            speed_steps: if scroll_speed && resp.hovered() { ui.input(|i| i.smooth_scroll_delta.y) as f64 / 50.0 } else { 0.0 },
        }
    }

    /// Advance the flying body by `dt` over terrain at `ground` (m above the ellipsoid).
    fn fly_step(&mut self, inp: &FlyInput, dt: f64, ground: f64) {
        let ell = self.ell();
        let Some(f) = &mut self.fly else { return };
        if let Some(agl) = self.spawn_agl {
            let touched = inp.forward != 0.0 || inp.right != 0.0 || inp.up != 0.0 || inp.yaw != 0.0 || inp.look_yaw != 0.0 || inp.look_pitch != 0.0;
            if touched {
                self.spawn_agl = None;
            } else {
                let g = f.geodetic(&ell);
                f.pos = geodesy::geodetic2ecef(geodesy::Geodetic { h: ground + agl, ..g }, &ell);
            }
        }
        f.update(dt, inp, &ell, ground);
        self.agl = f.geodetic(&ell).h - ground;
    }

    fn hud(&self, ui: &egui::Ui, rect: egui::Rect) {
        let Some(f) = &self.fly else { return };
        if self.nav == Nav::Orbit {
            return;
        }
        let g = f.geodetic(&self.ell());
        let text = format!(
            "{}   {:.0} km/h\nalt {}  above ground {}\nhdg {:03.0}°  pitch {:+.0}°  roll {:+.0}°\n{:.4}°, {:.4}°",
            if f.mode == FlyMode::Plane { "PLANE" } else { "FREE FLIGHT" },
            f.speed * 3.6,
            fmt_dist(g.h),
            fmt_dist(self.agl),
            f.heading.to_degrees(),
            f.pitch.to_degrees(),
            f.roll.to_degrees(),
            g.lat.to_degrees(),
            g.lon.to_degrees()
        );
        let pos = rect.left_top() + egui::vec2(12.0, 10.0);
        let font = egui::FontId::monospace(13.0);
        ui.painter().text(pos + egui::vec2(1.0, 1.0), egui::Align2::LEFT_TOP, &text, font.clone(), egui::Color32::from_black_alpha(200));
        ui.painter().text(pos, egui::Align2::LEFT_TOP, &text, font, egui::Color32::from_rgb(230, 240, 230));
        if self.tab == Tab::Map {
            let c = rect.center();
            let stroke = egui::Stroke::new(1.5, egui::Color32::from_rgba_unmultiplied(230, 240, 230, 160));
            ui.painter().line_segment([c - egui::vec2(18.0, 0.0), c - egui::vec2(6.0, 0.0)], stroke);
            ui.painter().line_segment([c + egui::vec2(6.0, 0.0), c + egui::vec2(18.0, 0.0)], stroke);
        }
    }

    fn map_view(&mut self, ui: &mut egui::Ui, frame: &eframe::Frame, rect: egui::Rect, resp: &egui::Response, dt: f64, typing: bool) {
        let ppp = ui.ctx().pixels_per_point();
        let (w, h) = ((rect.width() * ppp).round() as u32, (rect.height() * ppp).round() as u32);
        let ell = self.ell();
        let exag = self.s.exaggeration as f64;
        let aspect = w.max(1) as f64 / h.max(1) as f64;
        let cf = if self.nav == Nav::Orbit {
            let m_per_pt = self.orbit.dist * self.orbit.fov_y / rect.height().max(1.0) as f64;
            if resp.dragged_by(egui::PointerButton::Primary) {
                let d = resp.drag_delta();
                self.orbit.pan(d.x as f64, d.y as f64, m_per_pt, &ell);
            }
            if resp.dragged_by(egui::PointerButton::Secondary) || resp.dragged_by(egui::PointerButton::Middle) {
                let d = resp.drag_delta();
                self.orbit.heading -= d.x as f64 * 0.005;
                self.orbit.tilt = (self.orbit.tilt + d.y as f64 * 0.004).clamp(0.0, 1.48);
            }
            if resp.hovered() {
                let scroll = ui.input(|i| i.smooth_scroll_delta.y) as f64;
                if scroll != 0.0 {
                    self.orbit.dist = (self.orbit.dist * (-scroll * 0.003).exp()).clamp(40.0, 6.0e7);
                }
            }
            // keep the target on the terrain (smoothly: finer tiles change it as they arrive)
            let th = self.globe.height_at(self.orbit.lat, self.orbit.lon, 22).unwrap_or(0.0).max(0.0) * exag;
            self.orbit.target_h += (th - self.orbit.target_h) * 0.25;
            let cf = self.orbit.frame(&ell, aspect);
            let g = geodesy::ecef2geodetic(cf.eye, &ell);
            self.agl = g.h - self.globe.height_at(g.lat, g.lon, 22).unwrap_or(0.0).max(0.0) * exag;
            cf
        } else {
            let inp = Self::fly_input(ui, resp, typing, true);
            let g = self.fly.as_ref().map(|f| f.geodetic(&ell)).unwrap();
            let ground = self.globe.height_at(g.lat, g.lon, 22).unwrap_or(0.0).max(0.0) * exag;
            self.fly_step(&inp, dt, ground);
            self.fly.as_ref().unwrap().frame(&ell, aspect, ground)
        };
        let rs = frame.wgpu_render_state().expect("wgpu").clone();
        {
            let mut r = rs.renderer.write();
            self.globe.render(&cf, &self.s, &self.svc, w, h, Some(&mut r));
        }
        self.eye_alt = geodesy::ecef2geodetic(cf.eye, &ell).h;
        if let Some(id) = self.globe.texture_id {
            ui.painter().image(id, rect, egui::Rect::from_min_max(egui::pos2(0.0, 0.0), egui::pos2(1.0, 1.0)), egui::Color32::WHITE);
        }
        let ndc_of = |p: egui::Pos2| DVec2::new(((p.x - rect.left()) / rect.width() * 2.0 - 1.0) as f64, (1.0 - (p.y - rect.top()) / rect.height() * 2.0) as f64);
        self.hover = resp.hover_pos().and_then(|p| self.globe.pick(&cf, ndc_of(p)));
        if self.nav == Nav::Orbit && resp.double_clicked() {
            if let Some((la, lo)) = resp.interact_pointer_pos().and_then(|p| self.globe.pick(&cf, ndc_of(p))) {
                (self.orbit.lat, self.orbit.lon) = (la, lo);
                self.orbit.dist = (self.orbit.dist * 0.35).max(200.0);
            }
        }
        self.last_cf = Some(cf);
    }

    fn camera_view(&mut self, ui: &mut egui::Ui, rect: egui::Rect, resp: &egui::Response, dt: f64, typing: bool) {
        if self.camview.is_none() && self.error.is_none() {
            match CameraView::start(ui.ctx(), &self.scn, &self.spec, self.scale, self.supersample, self.svc.store.clone(), self.svc.clone()) {
                Ok(c) => self.camview = Some(c),
                Err(e) => self.error = Some(format!("camera view: {e:#}")),
            }
        }
        let ground = self.camview.as_ref().and_then(|c| c.ground()).unwrap_or(0.0).max(0.0);
        let inp = Self::fly_input(ui, resp, typing, true);
        self.fly_step(&inp, dt, ground);
        let wall = self.started.elapsed().as_secs_f64();
        if let (Some(c), Some(f)) = (&mut self.camview, &self.fly) {
            let ell = self.globe.ellipsoid();
            let pose = render::Pose { t: wall, geo: f.geodetic(&ell), q_ned_body: geodesy::euler_zyx_to_quat(f.heading, f.pitch, f.roll) };
            c.request(pose, wall, self.s.dynamic);
            c.show(ui, rect);
        }
    }
}

fn fmt_dist(m: f64) -> String {
    if m.abs() >= 10_000.0 {
        format!("{:.0} km", m / 1000.0)
    } else {
        format!("{m:.0} m")
    }
}

impl eframe::App for App {
    fn ui(&mut self, ui: &mut egui::Ui, frame: &mut eframe::Frame) {
        let now = Instant::now();
        let dt = now.duration_since(self.last_frame).as_secs_f64();
        self.frame_ms = if self.frame_ms == 0.0 { dt * 1000.0 } else { 0.9 * self.frame_ms + 100.0 * dt };
        self.last_frame = now;
        let typing = ui.ctx().egui_wants_keyboard_input();
        if !typing && ui.input(|i| i.key_pressed(egui::Key::M)) {
            self.set_tab(if self.tab == Tab::Map { Tab::Camera } else { Tab::Map });
        }
        if !typing && ui.input(|i| i.key_pressed(egui::Key::F)) {
            let next = match (self.nav, self.tab) {
                (Nav::Orbit, _) => Nav::Free,
                (Nav::Free, _) => Nav::Plane,
                (Nav::Plane, Tab::Map) => Nav::Orbit,
                (Nav::Plane, Tab::Camera) => Nav::Free,
            };
            self.set_nav(next);
        }
        egui::Panel::top("bar").show(ui, |ui| self.top_bar(ui));
        egui::Panel::left("panel").resizable(true).default_size(280.0).show(ui, |ui| {
            egui::ScrollArea::vertical().show(ui, |ui| self.side_panel(ui));
        });
        egui::CentralPanel::no_frame().show(ui, |ui| {
            let rect = ui.available_rect_before_wrap();
            let resp = ui.allocate_rect(rect, egui::Sense::click_and_drag());
            match self.tab {
                Tab::Map => self.map_view(ui, frame, rect, &resp, dt, typing),
                Tab::Camera => self.camera_view(ui, rect, &resp, dt, typing),
            }
            self.hud(ui, rect);
        });
        ui.ctx().request_repaint();
    }
}
