[package]
name = "tilestore"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "XYZ terrain tile pyramid stored in a single HDF5 file"

[dependencies]
geodesy.workspace = true
h5.workspace = true
flate2.workspace = true
rayon.workspace = true
anyhow.workspace = true
parking_lot.workspace = true
